# Generated by Django 5.1 on 2024-09-15 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tradable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volumne_currency', models.FloatField()),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('tradable', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backtesting.tradable')),
            ],
        ),
    ]
