# Generated by Django 5.1 on 2024-09-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtesting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin', models.FloatField()),
                ('takeProfit', models.FloatField()),
                ('stopLoss', models.FloatField()),
            ],
        ),
    ]
